// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportMeet.Infrastructure.Persistence;

#nullable disable

namespace SportMeet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921064431_Init_Tables")]
    partial class Init_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportMeet.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("place_id");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("skill_level");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Australia/Melbourne")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("venue_name");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_events_host_id");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("events_start_at_idx")
                        .HasFilter("status = 'Scheduled'");

                    b.HasIndex("Lat", "Lng")
                        .HasDatabaseName("events_geo_bbox_idx");

                    b.HasIndex("SportId", "StartAt")
                        .HasDatabaseName("events_sport_start_idx");

                    b.ToTable("events", "sportsmeet", t =>
                        {
                            t.HasCheckConstraint("events_cost_check", "cost IS NULL OR cost >= 0");

                            t.HasCheckConstraint("events_description_length_check", "description IS NULL OR char_length(description) <= 2000");

                            t.HasCheckConstraint("events_lat_check", "lat BETWEEN -90 AND 90");

                            t.HasCheckConstraint("events_lng_check", "lng BETWEEN -180 AND 180");

                            t.HasCheckConstraint("events_participants_check", "max_participants BETWEEN 2 AND 50");

                            t.HasCheckConstraint("events_skill_level_check", "skill_level IN ('Beginner', 'Intermediate', 'Advanced')");

                            t.HasCheckConstraint("events_status_check", "status IN ('Scheduled', 'Cancelled', 'Completed')");

                            t.HasCheckConstraint("events_time_range_check", "end_at > start_at");

                            t.HasCheckConstraint("events_title_length_check", "char_length(title) BETWEEN 3 AND 80");

                            t.HasCheckConstraint("events_venue_length_check", "char_length(venue_name) BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("SportMeet.Domain.Entities.EventParticipant", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("EventId", "UserId")
                        .HasName("pk_event_participants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_participants_user_id");

                    b.ToTable("event_participants", "sportsmeet");
                });

            modelBuilder.Entity("SportMeet.Domain.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_sports");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sports_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sports_slug");

                    b.ToTable("sports", "sportsmeet", t =>
                        {
                            t.HasCheckConstraint("sports_slug_lower_check", "slug = lower(slug)");
                        });
                });

            modelBuilder.Entity("SportMeet.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth_uid");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("photo_url");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AuthUid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth_uid");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "sportsmeet");
                });

            modelBuilder.Entity("SportMeet.Infrastructure.Persistence.VwEventFeed", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("current_participants");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_name");

                    b.Property<string>("HostPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("host_photo_url");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text")
                        .HasColumnName("place_id");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_level");

                    b.Property<string>("SportIcon")
                        .HasColumnType("text")
                        .HasColumnName("sport_icon");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sport_name");

                    b.Property<string>("SportSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sport_slug");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("venue_name");

                    b.ToTable((string)null);

                    b.ToView("v_event_feed", "sportsmeet");
                });

            modelBuilder.Entity("SportMeet.Domain.Entities.Event", b =>
                {
                    b.HasOne("SportMeet.Domain.Entities.User", "Host")
                        .WithMany("HostedEvents")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_users_host_id");

                    b.HasOne("SportMeet.Domain.Entities.Sport", "Sport")
                        .WithMany("Events")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_sports_sport_id");

                    b.Navigation("Host");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportMeet.Domain.Entities.EventParticipant", b =>
                {
                    b.HasOne("SportMeet.Domain.Entities.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_participants_events_event_id");

                    b.HasOne("SportMeet.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_participants_users_user_id");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportMeet.Domain.Entities.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("SportMeet.Domain.Entities.Sport", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("SportMeet.Domain.Entities.User", b =>
                {
                    b.Navigation("HostedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
